#!/usr/bin/env bash
# prerelease.sh – Generate docs/GODOC.md from go doc output.
#
# Usage:
#   ./scripts/prerelease.sh
#
# Output:
#   docs/GODOC.md  – single-page API reference for all internal packages.
#
# This script is intentionally dependency-free (only uses standard go toolchain).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/docs/GODOC.md"

PACKAGES=(
  "kube-less/internal/scheduler"
  "kube-less/internal/cri"
  "kube-less/internal/probe"
  "kube-less/internal/api"
  "kube-less/internal/network"
  "kube-less/cmd/kube-less"
)

cd "$REPO_ROOT"

echo "Generating $OUT ..."

{
  echo "# kube-less – API Reference"
  echo ""
  echo "> Auto-generated by \`scripts/prerelease.sh\` on $(date -u +%Y-%m-%d)."
  echo "> Re-run before each release: \`make docs\`"
  echo ""
  echo "---"
  echo ""

  for pkg in "${PACKAGES[@]}"; do
    # Short display name (last two path segments)
    short="${pkg#kube-less/}"

    echo "## \`$short\`"
    echo ""
    echo '```'
    go doc -all "$pkg" 2>/dev/null || echo "(no exported symbols)"
    echo '```'
    echo ""
    echo "---"
    echo ""
  done
} > "$OUT"

echo "Done: $OUT ($(wc -l < "$OUT") lines)"
